### ISSUE TITLE
Cannot draw while in Fullscreen Projector mode

### ISSUE THREAD

**Issue by HeyItsLollie** [katarai/obs-whiteboard-lua#1]
First of all, thank you for maintaining this script! OBS has needed a whiteboard feature for a long time, and mwelsh's original script was the first option I'd found that had figured out how to draw directly in the projector. Very happy to see the new size/color options and eraser toggle in this version.

-----
I'm on OBS 25.0.4 (64-bit, Win 10 Pro, 1903), and for whatever reason, the Fullscreen Projector doesn't accept drawing input - not from my mouse or my tablet.

I *can* draw in the Windowed Projector without any issues, so I have a stable workaround for the moment!

**Comment by katarai** [comment]
Odd. I'd tested that previously and it'd been working. I must've broken it at some point before release. Thanks for pointing it out!

**Comment by katarai** [comment]
Fixed in v1.3a.
