### ISSUE TITLE
SUPPORT OBS 29.0.2

### ISSUE THREAD

**Issue by wakeupneooo** [katarai/obs-whiteboard-lua#4]

**Comment by wakeupneooo** [comment]
any news

**Comment by katarai** [comment]
It seems to work on my install of OBS 29.1.1.

I'll do some more testing on another system (with fresh installs), but I've so far been unable to reproduce the issue.

**Comment by katarai** [comment]
I did a clean install on a different PC and loaded the script directly from my downloads folder.

Everything works as expected.

I can't reproduce these failures on my end, so I'm going to mark this issue as closed. If you have more information about what might be causing issues, please do let me know.
